import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'NextJS + Mongo App',
  description: 'Generated by buildmystack',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'system-ui, sans-serif', margin: 0, padding: 0 }}>
        <Navbar />
        <main style={{ padding: '20px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
